// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLawyerFinal.Models;

#nullable disable

namespace SmartLawyerFinal.Migrations
{
    [DbContext(typeof(LegalManagementContext))]
    [Migration("20260404225946_AddCreatedAtToClientOnly")]
    partial class AddCreatedAtToClientOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_CI_AI")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartLawyerFinal.Models.ActualPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FeeId")
                        .HasColumnType("int");

                    b.Property<int?>("InstallmentId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("كاش");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReceivedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ActualPa__3214EC079243D2AE");

                    b.HasIndex("FeeId");

                    b.HasIndex("InstallmentId");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex(new[] { "ReceiptNumber" }, "UQ__ActualPa__C08AFDAB7C3F98C9")
                        .IsUnique()
                        .HasFilter("[ReceiptNumber] IS NOT NULL");

                    b.ToTable("ActualPayments", "Finance");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.AdminExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("ExpenseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaidBy")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK__AdminExp__3214EC0712846B0C");

                    b.HasIndex("CaseId");

                    b.HasIndex("PaidBy");

                    b.ToTable("AdminExpenses", "Finance");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Appeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AppealDate")
                        .HasColumnType("date");

                    b.Property<string>("AppealNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AppealType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AssignedLawyerId")
                        .HasColumnType("int");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Grounds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ResultDate")
                        .HasColumnType("date");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Appeals__3214EC0717FB0C75");

                    b.HasIndex("AssignedLawyerId");

                    b.HasIndex("CaseId");

                    b.HasIndex("CourtId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "AppealNumber" }, "UQ__Appeals__9802DB2581E9FC9B")
                        .IsUnique()
                        .HasFilter("[AppealNumber] IS NOT NULL");

                    b.ToTable("Appeals", "Legal");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchiveNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ArchivedBy")
                        .HasColumnType("int");

                    b.Property<int>("AssignedLawyerId")
                        .HasColumnType("int");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CaseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("OpenDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<string>("Stage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Cases__3214EC077FEDE386");

                    b.HasIndex("ArchivedBy");

                    b.HasIndex("AssignedLawyerId");

                    b.HasIndex("CaseTypeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CourtId");

                    b.HasIndex("DeptId");

                    b.HasIndex("StatusId");

                    b.ToTable("Cases", "Legal");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.CaseLawyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("محامي مساعد");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CaseLawy__3214EC0729B90EEA");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CaseId", "UserId" }, "UQ_CaseLawyers")
                        .IsUnique();

                    b.ToTable("CaseLawyers", "Legal");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.CaseOpponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("OpponentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CaseOppo__3214EC0713244ACE");

                    b.HasIndex("OpponentId");

                    b.HasIndex(new[] { "CaseId", "OpponentId" }, "UQ_CaseOpponents")
                        .IsUnique();

                    b.ToTable("CaseOpponents", "Legal");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.CaseStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasDefaultValue("#1D9E75");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("مفتوحة");

                    b.HasKey("Id")
                        .HasName("PK__CaseStat__3214EC07B5F2F383");

                    b.HasIndex(new[] { "StatusName" }, "UQ__CaseStat__05E7698A51AACFCC")
                        .IsUnique();

                    b.ToTable("CaseStatuses", "Lookup");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.CaseType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__CaseType__3214EC075B6A89A7");

                    b.HasIndex(new[] { "TypeName" }, "UQ__CaseType__D4E7DFA851ADBB57")
                        .IsUnique();

                    b.ToTable("CaseTypes", "Lookup");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("فرد");

                    b.Property<string>("CommercialReg")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("JobTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("char(14)")
                        .IsFixedLength();

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__Clients__3214EC072E76F1EE");

                    b.HasIndex(new[] { "CommercialReg" }, "UQ__Clients__5553E82743175A53")
                        .IsUnique()
                        .HasFilter("[CommercialReg] IS NOT NULL");

                    b.HasIndex(new[] { "NationalId" }, "UQ__Clients__E9AA32FAC4ED8D46")
                        .IsUnique()
                        .HasFilter("[NationalId] IS NOT NULL");

                    b.ToTable("Clients", "Legal");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id")
                        .HasName("PK__Courts__3214EC0774F0030F");

                    b.HasIndex(new[] { "CourtName" }, "UQ__Courts__5750888E36409F76")
                        .IsUnique();

                    b.ToTable("Courts", "Lookup");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JudgeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Departme__3214EC07056CED17");

                    b.HasIndex("CourtId");

                    b.HasIndex(new[] { "DeptName", "CourtId" }, "UQ_Departments")
                        .IsUnique();

                    b.ToTable("Departments", "Lookup");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ArchivedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ArchivedBy")
                        .HasColumnType("int");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Document__3214EC07983567AD");

                    b.HasIndex("ArchivedBy");

                    b.HasIndex("CaseId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Documents", "Docs");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.DocumentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Document__3214EC0780986D55");

                    b.HasIndex("AddedBy");

                    b.ToTable("DocumentTemplates", "Docs");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Fee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Fees__3214EC0761BC1105");

                    b.HasIndex("CaseId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Fees", "Finance");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Hearing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("قادم");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HearingDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("HearingType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("جلسة");

                    b.Property<string>("JudgeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("NextHearingDate")
                        .HasColumnType("date");

                    b.Property<string>("NextHearingPeriod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComputedColumnSql("(case when datepart(hour,[HearingDateTime])<(12) then N'صباحي' else N'مسائي' end)", false);

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Hearings__3214EC075601EDF7");

                    b.HasIndex("CaseId");

                    b.HasIndex("CourtId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeptId");

                    b.ToTable("Hearings", "Legal");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.LegalLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__LegalLib__3214EC072F97D00B");

                    b.HasIndex("AddedBy");

                    b.ToTable("LegalLibrary", "Docs");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("عامة");

                    b.Property<int>("RelatedId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Notes__3214EC07523701A4");

                    b.HasIndex("UserId");

                    b.ToTable("Notes", "Legal");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Opponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("char(14)")
                        .IsFixedLength();

                    b.Property<string>("OpponentLawyerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OpponentLawyerPhone")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__Opponent__3214EC075B5771E3");

                    b.HasIndex(new[] { "NationalId" }, "UQ__Opponent__E9AA32FA65B02F64")
                        .IsUnique()
                        .HasFilter("[NationalId] IS NOT NULL");

                    b.ToTable("Opponents", "Legal");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.PaymentSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("FeeId")
                        .HasColumnType("int");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("معلق");

                    b.HasKey("Id")
                        .HasName("PK__PaymentS__3214EC070A799146");

                    b.HasIndex(new[] { "FeeId", "InstallmentNumber" }, "UQ_PaySched_Inst")
                        .IsUnique();

                    b.ToTable("PaymentSchedule", "Finance");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Reports__3214EC0721CC3C25");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("Reports", "Core");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("محامي");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07B922EC91");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160D0D90D89")
                        .IsUnique();

                    b.ToTable("Roles", "Core");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<string>("NationalId")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("char(14)")
                        .IsFixedLength();

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecondNumber")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0763A419AA");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__Users__85FB4E38776812BE")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053418FB8C99")
                        .IsUnique();

                    b.HasIndex(new[] { "NationalId" }, "UQ__Users__E9AA32FA09CF1B85")
                        .IsUnique()
                        .HasFilter("[NationalId] IS NOT NULL");

                    b.ToTable("Users", "Core");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.ActualPayment", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.Fee", "Fee")
                        .WithMany("ActualPayments")
                        .HasForeignKey("FeeId")
                        .IsRequired()
                        .HasConstraintName("FK_ActPay_Fee");

                    b.HasOne("SmartLawyerFinal.Models.PaymentSchedule", "Installment")
                        .WithMany("ActualPayments")
                        .HasForeignKey("InstallmentId")
                        .HasConstraintName("FK_ActPay_Installment");

                    b.HasOne("SmartLawyerFinal.Models.User", "ReceivedByNavigation")
                        .WithMany("ActualPayments")
                        .HasForeignKey("ReceivedBy")
                        .IsRequired()
                        .HasConstraintName("FK_ActPay_RecBy");

                    b.Navigation("Fee");

                    b.Navigation("Installment");

                    b.Navigation("ReceivedByNavigation");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.AdminExpense", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.Case", "Case")
                        .WithMany("AdminExpenses")
                        .HasForeignKey("CaseId")
                        .IsRequired()
                        .HasConstraintName("FK_AdminExp_Case");

                    b.HasOne("SmartLawyerFinal.Models.User", "PaidByNavigation")
                        .WithMany("AdminExpenses")
                        .HasForeignKey("PaidBy")
                        .IsRequired()
                        .HasConstraintName("FK_AdminExp_PaidBy");

                    b.Navigation("Case");

                    b.Navigation("PaidByNavigation");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Appeal", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.User", "AssignedLawyer")
                        .WithMany("Appeals")
                        .HasForeignKey("AssignedLawyerId")
                        .IsRequired()
                        .HasConstraintName("FK_Appeals_Lawyer");

                    b.HasOne("SmartLawyerFinal.Models.Case", "Case")
                        .WithMany("Appeals")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Appeals_Case");

                    b.HasOne("SmartLawyerFinal.Models.Court", "Court")
                        .WithMany("Appeals")
                        .HasForeignKey("CourtId")
                        .IsRequired()
                        .HasConstraintName("FK_Appeals_Court");

                    b.HasOne("SmartLawyerFinal.Models.CaseStatus", "Status")
                        .WithMany("Appeals")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Appeals_Status");

                    b.Navigation("AssignedLawyer");

                    b.Navigation("Case");

                    b.Navigation("Court");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Case", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.User", "ArchivedByNavigation")
                        .WithMany("CaseArchivedByNavigations")
                        .HasForeignKey("ArchivedBy")
                        .HasConstraintName("FK_Cases_ArchivedBy");

                    b.HasOne("SmartLawyerFinal.Models.User", "AssignedLawyer")
                        .WithMany("CaseAssignedLawyers")
                        .HasForeignKey("AssignedLawyerId")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Lawyer");

                    b.HasOne("SmartLawyerFinal.Models.CaseType", "CaseType")
                        .WithMany("Cases")
                        .HasForeignKey("CaseTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_CaseType");

                    b.HasOne("SmartLawyerFinal.Models.Client", "Client")
                        .WithMany("Cases")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Client");

                    b.HasOne("SmartLawyerFinal.Models.Court", "Court")
                        .WithMany("Cases")
                        .HasForeignKey("CourtId")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Court");

                    b.HasOne("SmartLawyerFinal.Models.Department", "Dept")
                        .WithMany("Cases")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK_Cases_Dept");

                    b.HasOne("SmartLawyerFinal.Models.CaseStatus", "Status")
                        .WithMany("Cases")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Status");

                    b.Navigation("ArchivedByNavigation");

                    b.Navigation("AssignedLawyer");

                    b.Navigation("CaseType");

                    b.Navigation("Client");

                    b.Navigation("Court");

                    b.Navigation("Dept");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.CaseLawyer", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.Case", "Case")
                        .WithMany("CaseLawyers")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CaseLawyers_Case");

                    b.HasOne("SmartLawyerFinal.Models.User", "User")
                        .WithMany("CaseLawyers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CaseLawyers_User");

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.CaseOpponent", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.Case", "Case")
                        .WithMany("CaseOpponents")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CaseOpponents_Case");

                    b.HasOne("SmartLawyerFinal.Models.Opponent", "Opponent")
                        .WithMany("CaseOpponents")
                        .HasForeignKey("OpponentId")
                        .IsRequired()
                        .HasConstraintName("FK_CaseOpponents_Opponent");

                    b.Navigation("Case");

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Department", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.Court", "Court")
                        .WithMany("Departments")
                        .HasForeignKey("CourtId")
                        .IsRequired()
                        .HasConstraintName("FK_Departments_Courts");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Document", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.User", "ArchivedByNavigation")
                        .WithMany("DocumentArchivedByNavigations")
                        .HasForeignKey("ArchivedBy")
                        .HasConstraintName("FK_Documents_ArchivedBy");

                    b.HasOne("SmartLawyerFinal.Models.Case", "Case")
                        .WithMany("Documents")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Documents_Case");

                    b.HasOne("SmartLawyerFinal.Models.User", "UploadedByNavigation")
                        .WithMany("DocumentUploadedByNavigations")
                        .HasForeignKey("UploadedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Documents_UploadedBy");

                    b.Navigation("ArchivedByNavigation");

                    b.Navigation("Case");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.DocumentTemplate", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.User", "AddedByNavigation")
                        .WithMany("DocumentTemplates")
                        .HasForeignKey("AddedBy")
                        .IsRequired()
                        .HasConstraintName("FK_DocumentTemplates_AddedBy");

                    b.Navigation("AddedByNavigation");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Fee", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.Case", "Case")
                        .WithMany("Fees")
                        .HasForeignKey("CaseId")
                        .IsRequired()
                        .HasConstraintName("FK_Fees_Case");

                    b.HasOne("SmartLawyerFinal.Models.Client", "Client")
                        .WithMany("Fees")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_Fees_Client");

                    b.HasOne("SmartLawyerFinal.Models.User", "CreatedByNavigation")
                        .WithMany("Fees")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Fees_CreatedBy");

                    b.Navigation("Case");

                    b.Navigation("Client");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Hearing", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.Case", "Case")
                        .WithMany("Hearings")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Hearings_Case");

                    b.HasOne("SmartLawyerFinal.Models.Court", "Court")
                        .WithMany("Hearings")
                        .HasForeignKey("CourtId")
                        .IsRequired()
                        .HasConstraintName("FK_Hearings_Court");

                    b.HasOne("SmartLawyerFinal.Models.User", "CreatedByNavigation")
                        .WithMany("Hearings")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Hearings_CreatedBy");

                    b.HasOne("SmartLawyerFinal.Models.Department", "Dept")
                        .WithMany("Hearings")
                        .HasForeignKey("DeptId")
                        .IsRequired()
                        .HasConstraintName("FK_Hearings_Dept");

                    b.Navigation("Case");

                    b.Navigation("Court");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.LegalLibrary", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.User", "AddedByNavigation")
                        .WithMany("LegalLibraries")
                        .HasForeignKey("AddedBy")
                        .IsRequired()
                        .HasConstraintName("FK_LegalLibrary_AddedBy");

                    b.Navigation("AddedByNavigation");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Note", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notes_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.PaymentSchedule", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.Fee", "Fee")
                        .WithMany("PaymentSchedules")
                        .HasForeignKey("FeeId")
                        .IsRequired()
                        .HasConstraintName("FK_PaySched_Fee");

                    b.Navigation("Fee");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Report", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.User", "GeneratedByNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("GeneratedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Reports_GeneratedBy");

                    b.Navigation("GeneratedByNavigation");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.User", b =>
                {
                    b.HasOne("SmartLawyerFinal.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Case", b =>
                {
                    b.Navigation("AdminExpenses");

                    b.Navigation("Appeals");

                    b.Navigation("CaseLawyers");

                    b.Navigation("CaseOpponents");

                    b.Navigation("Documents");

                    b.Navigation("Fees");

                    b.Navigation("Hearings");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.CaseStatus", b =>
                {
                    b.Navigation("Appeals");

                    b.Navigation("Cases");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.CaseType", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Client", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Fees");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Court", b =>
                {
                    b.Navigation("Appeals");

                    b.Navigation("Cases");

                    b.Navigation("Departments");

                    b.Navigation("Hearings");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Department", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Hearings");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Fee", b =>
                {
                    b.Navigation("ActualPayments");

                    b.Navigation("PaymentSchedules");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Opponent", b =>
                {
                    b.Navigation("CaseOpponents");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.PaymentSchedule", b =>
                {
                    b.Navigation("ActualPayments");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartLawyerFinal.Models.User", b =>
                {
                    b.Navigation("ActualPayments");

                    b.Navigation("AdminExpenses");

                    b.Navigation("Appeals");

                    b.Navigation("CaseArchivedByNavigations");

                    b.Navigation("CaseAssignedLawyers");

                    b.Navigation("CaseLawyers");

                    b.Navigation("DocumentArchivedByNavigations");

                    b.Navigation("DocumentTemplates");

                    b.Navigation("DocumentUploadedByNavigations");

                    b.Navigation("Fees");

                    b.Navigation("Hearings");

                    b.Navigation("LegalLibraries");

                    b.Navigation("Notes");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
